const price = {
	Car: 20,
	Bike: 10,
	Truck: 50,
};

const listPark = [
	[
		{ id: 1, car: null, name: 'A01', type: 'Car' },
		{ id: 2, car: null, name: 'A02', type: 'Car' },
		{ id: 3, car: null, name: 'A03', type: 'Car' },
		{ id: 4, car: null, name: 'A04', type: 'Truck' },
		{ id: 5, car: null, name: 'A05', type: 'Truck' },
		{ id: 6, car: null, name: 'A08', type: 'Car' },
		{ id: 7, car: null, name: 'A09', type: 'Bike' },
		{ id: 8, car: null, name: 'A10', type: 'Car' },
		{ id: 9, car: null, name: 'A06', type: 'Truck' },
		{ id: 10, car: null, name: 'A11', type: 'Car' },
		{ id: 11, car: null, name: 'A12', type: 'Car' },
		{ id: 12, car: null, name: 'A13', type: 'Car' },
		{ id: 13, car: null, name: 'A07', type: 'Truck' },
		{ id: 14, car: null, name: 'A14', type: 'Car' },
		{ id: 15, car: null, name: 'A15', type: 'Car' },
		{ id: 16, car: null, name: 'A16', type: 'Truck' },
	],
	[
		{ id: 17, car: null, name: 'B01', type: 'Car' },
		{ id: 18, car: null, name: 'B02', type: 'Bike' },
		{ id: 19, car: null, name: 'B03', type: 'Car' },
		{ id: 20, car: null, name: 'B04', type: 'Car' },
		{ id: 21, car: null, name: 'B05', type: 'Truck' },
		{ id: 22, car: null, name: 'B06', type: 'Car' },
		{ id: 23, car: null, name: 'B07', type: 'Truck' },
		{ id: 24, car: null, name: 'B08', type: 'Bike' },
		{ id: 25, car: null, name: 'B09', type: 'Car' },
		{ id: 26, car: null, name: 'B10', type: 'Car' },
		{ id: 27, car: null, name: 'B11', type: 'Car' },
		{ id: 28, car: null, name: 'B12', type: 'Car' },
		{ id: 29, car: null, name: 'B13', type: 'Car' },
		{ id: 30, car: null, name: 'B14', type: 'Truck' },
		{ id: 31, car: null, name: 'B15', type: 'Car' },
		{ id: 32, car: null, name: 'B16', type: 'Car' },
	],
	[
		{ id: 33, car: null, name: 'C01', type: 'Truck' },
		{ id: 34, car: null, name: 'C02', type: 'Bike' },
		{ id: 35, car: null, name: 'C03', type: 'Truck' },
		{ id: 36, car: null, name: 'C04', type: 'Car' },
		{ id: 37, car: null, name: 'C05', type: 'Car' },
		{ id: 38, car: null, name: 'C06', type: 'Car' },
		{ id: 39, car: null, name: 'C07', type: 'Truck' },
		{ id: 40, car: null, name: 'C08', type: 'Car' },
		{ id: 41, car: null, name: 'C09', type: 'Car' },
		{ id: 42, car: null, name: 'C10', type: 'Car' },
		{ id: 43, car: null, name: 'C11', type: 'Bike' },
		{ id: 44, car: null, name: 'C12', type: 'Car' },
		{ id: 45, car: null, name: 'C13', type: 'Car' },
		{ id: 46, car: null, name: 'C14', type: 'Bike' },
		{ id: 47, car: null, name: 'C15', type: 'Car' },
		{ id: 48, car: null, name: 'C16', type: 'Car' },
	],
];
